Repository FOSSEE/online_test, pull requests merged in 2018-07, with the labels that each got.

#489 Get questions using tags during question paper setup
  yaksh/forms.py
  yaksh/static/yaksh/js/question_paper_creation.js
  yaksh/templates/yaksh/ajax_question_filter.html
  yaksh/templates/yaksh/design_questionpaper.html
  yaksh/test_views.py
  yaksh/views.py
Labels: Priority: Critical, Type: Feature

#487 Download course content for offline view
  yaksh/file_utils.py
  yaksh/forms.py
  yaksh/models.py
  yaksh/static/yaksh/css/lesson.css
  yaksh/static/yaksh/css/offline.css
  yaksh/static/yaksh/css/video-js.css
  yaksh/static/yaksh/js/jquery-1.4.2.min.js
  yaksh/static/yaksh/js/video.js
  yaksh/templates/manage.html
  yaksh/templates/yaksh/add_lesson.html
  yaksh/templates/yaksh/courses.html
  yaksh/templates/yaksh/index.html
  yaksh/templates/yaksh/module.html
  yaksh/templates/yaksh/quizzes_user.html
  yaksh/templates/yaksh/show_video.html
  yaksh/templates/yaksh/unit.html
  yaksh/templatetags/custom_filters.py
  yaksh/test_views.py
  yaksh/urls.py
  yaksh/views.py
Labels: Priority: High, Type: Feature

#497 Change README
  README.rst
  README_production.rst
Labels: Priority: High, Type: Documentation

#496 Question upload can take yaml and zip files
  yaksh/documentation/moderator_docs/creating_question.rst
  yaksh/file_utils.py
  yaksh/fixtures/demo_questions.zip
  yaksh/models.py
  yaksh/templates/yaksh/showquestions.html
  yaksh/test_models.py
  yaksh/test_views.py
  yaksh/views.py
Labels: Priority: High, Type: Enhancement

#491 Raise appropriate exceptions for C and Java language to the Grader
  yaksh/cpp_code_evaluator.py
  yaksh/cpp_stdio_evaluator.py
  yaksh/error_messages.py
  yaksh/evaluator_tests/test_c_cpp_evaluation.py
  yaksh/evaluator_tests/test_java_evaluation.py
  yaksh/grader.py
  yaksh/java_code_evaluator.py
  yaksh/java_stdio_evaluator.py
  yaksh/models.py
  yaksh/test_models.py
Labels: Priority: High, Type: Enhancement

#480 [Role based implementation] Allow moderator to switch between student and moderator roles
  yaksh/evaluator_tests/test_simple_question_types.py
  yaksh/live_server_tests/load_test.py
  yaksh/management/commands/create_moderator.py
  yaksh/models.py
  yaksh/templates/yaksh/moderator_dashboard.html
  yaksh/templates/yaksh/quizzes_user.html
  yaksh/templatetags/test_custom_filters.py
  yaksh/test_models.py
  yaksh/test_views.py
  yaksh/urls.py
  yaksh/views.py
Labels: Priority: High, Type: Feature

#498 release v0.9
  CHANGELOG.txt
  online_test/__init__.py
  yaksh/evaluator_tests/test_python_evaluation.py
  yaksh/file_utils.py
  yaksh/fixtures/demo_questions.zip
  yaksh/live_server_tests/selenium_test.py
  yaksh/migrations/0013_release_0_9_0.py
  yaksh/models.py
  yaksh/test_views.py
Labels: Priority: Critical, Type: Release

#503 Add a redirect from url / to /exam
  online_test/urls.py
  online_test/views.py
Labels: Priority: High, Type: Enhancement

#502 Fix assignment upload
  yaksh/models.py
  yaksh/templates/yaksh/grade_user.html
  yaksh/templates/yaksh/view_answerpaper.html
  yaksh/test_models.py
  yaksh/test_views.py
  yaksh/urls.py
  yaksh/views.py
Labels: Priority: High, Type: Bug

#509 Remove yaksh-cli
  setup.py
  yaksh/demo_templates/demo_settings.py
  yaksh/demo_templates/demo_urls.py
  yaksh/scripts/cli.py
Labels: Priority: Low, Type: Enhancement

#507 Remove references to non existent static CSS files
  yaksh/static/yaksh/js/question_paper_creation.js
  yaksh/templates/yaksh/add_course.html
  yaksh/templates/yaksh/add_exercise.html
  yaksh/templates/yaksh/add_quiz.html
  yaksh/templates/yaksh/addteacher.html
  yaksh/templates/yaksh/ajax_marks.html
  yaksh/templates/yaksh/showusers.html
Labels: Priority: Low, Type: Enhancement

#519 Fix spelling error: choosen to chosen
  yaksh/documentation/moderator_docs/creating_lessons_modules.rst
  yaksh/static/yaksh/js/design_course.js
  yaksh/templates/yaksh/add_module.html
  yaksh/templates/yaksh/design_course_session.html
  yaksh/test_views.py
  yaksh/views.py
Labels: Priority: Low, Type: Enhancement
