Repository FOSSEE/online_test, pull requests merged in 2018-06, with the labels that each got.

#477 Add recipients to BCC field in send_bulk_mail function
  yaksh/send_emails.py
  yaksh/test_views.py
Labels: Priority: Low, Type: Enhancement

#461 Quiz Completion Status
  yaksh/models.py
  yaksh/test_models.py
Labels: Priority: Critical, Type: Bug

#469 Enhance course status
  yaksh/models.py
  yaksh/static/yaksh/js/course.js
  yaksh/templates/yaksh/complete.html
  yaksh/templates/yaksh/course_detail.html
  yaksh/templates/yaksh/course_modules.html
  yaksh/templates/yaksh/show_video.html
  yaksh/templates/yaksh/user_status.html
  yaksh/templatetags/custom_filters.py
  yaksh/test_models.py
  yaksh/test_views.py
  yaksh/urls.py
  yaksh/views.py
Labels: Priority: High, Type: Enhancement

#482 Pep8 changes
  grades/tests/test_models.py
  grades/tests/test_views.py
  grades/views.py
  online_test/settings.py
  online_test/urls.py
  online_test/wsgi.py
  tasks.py
  yaksh/admin.py
  yaksh/base_evaluator.py
  yaksh/bash_code_evaluator.py
  yaksh/bash_stdio_evaluator.py
  yaksh/cpp_code_evaluator.py
  yaksh/cpp_stdio_evaluator.py
  yaksh/decorators.py
  yaksh/documentation/conf.py
  yaksh/error_messages.py
  yaksh/evaluator_tests/test_bash_evaluation.py
  yaksh/evaluator_tests/test_c_cpp_evaluation.py
  yaksh/evaluator_tests/test_grader_evaluation.py
  yaksh/evaluator_tests/test_java_evaluation.py
  yaksh/evaluator_tests/test_python_stdio_evaluator.py
  yaksh/evaluator_tests/test_scilab_evaluation.py
  yaksh/evaluator_tests/test_simple_question_types.py
  yaksh/file_utils.py
  yaksh/hook_evaluator.py
  yaksh/java_code_evaluator.py
  yaksh/java_stdio_evaluator.py
  yaksh/language_registry.py
  yaksh/management/commands/create_moderator.py
  yaksh/middleware/one_session_per_user.py
  yaksh/middleware/user_time_zone.py
  yaksh/models.py
  yaksh/python_stdio_evaluator.py
  yaksh/scilab_code_evaluator.py
  yaksh/send_emails.py
  yaksh/settings.py
  yaksh/stdio_evaluator.py
  yaksh/templatetags/test_custom_filters.py
  yaksh/test_models.py
  yaksh/test_views.py
  yaksh/tests/test_code_server.py
  yaksh/urls.py
  yaksh/views.py
Labels: Priority: High, Type: Enhancement

#484 Release 0.8.1
  CHANGELOG.txt
  online_test/__init__.py
  yaksh/migrations/0012_release_0_8_1.py
Labels: Priority: High, Type: Release
