Repository FOSSEE/online_test, pull requests merged in 2018-03, with the labels that each got.

#457 Specify tornado version to 4.5.3
  requirements/requirements-codeserver.txt
Labels: Type: Bug

#429 Shuffle testcases
  yaksh/evaluator_tests/test_simple_question_types.py
  yaksh/forms.py
  yaksh/models.py
  yaksh/static/yaksh/js/add_question.js
  yaksh/templates/yaksh/design_questionpaper.html
  yaksh/templates/yaksh/user_data.html
  yaksh/templates/yaksh/view_answerpaper.html
  yaksh/templatetags/custom_filters.py
  yaksh/test_models.py
  yaksh/views.py
Labels: Type: Feature

#448 Update documentation
  yaksh/documentation/conf.py
  yaksh/documentation/images/add_exercise.jpg
  yaksh/documentation/images/add_lesson.jpg
  yaksh/documentation/images/add_question.jpg
  yaksh/documentation/images/add_quiz.jpg
  yaksh/documentation/images/course_details_features.jpg
  yaksh/documentation/images/course_features.jpg
  yaksh/documentation/images/cpp_standard_testcase.jpg
  yaksh/documentation/images/create_course.jpg
  yaksh/documentation/images/design_course.jpg
  yaksh/documentation/images/design_module.jpg
  yaksh/documentation/images/design_questionpaper.jpg
  yaksh/documentation/images/embed_video.jpg
  yaksh/documentation/images/float_testcase.jpg
  yaksh/documentation/images/hook_testcase.jpg
  yaksh/documentation/images/integer_testcase.jpg
  yaksh/documentation/images/java_standard_testcase.jpg
  yaksh/documentation/images/moderator_dashboard.jpg
  yaksh/documentation/images/python_standard_testcase.jpg
  yaksh/documentation/images/questions.jpg
  yaksh/documentation/images/stdio_testcase.jpg
  yaksh/documentation/images/string_testcase.jpg
  yaksh/documentation/images/view_lessons.jpg
  yaksh/documentation/images/view_modules.jpg
  yaksh/documentation/images/view_quizzes.jpg
  yaksh/documentation/index.rst
  yaksh/documentation/installation.rst
  yaksh/documentation/moderator_dashboard.rst
  yaksh/documentation/moderator_docs/creating_course.rst
  yaksh/documentation/moderator_docs/creating_lessons_modules.rst
  yaksh/documentation/moderator_docs/creating_question.rst
  yaksh/documentation/moderator_docs/creating_quiz.rst
Labels: Type: Documentation

#446 Fix clone course
  yaksh/models.py
  yaksh/templates/yaksh/complete.html
  yaksh/templates/yaksh/courses.html
  yaksh/templates/yaksh/design_course_session.html
  yaksh/test_views.py
  yaksh/urls.py
  yaksh/views.py
Labels: Type: Enhancement

#450 Student Dashboard Changes
  yaksh/forms.py
  yaksh/models.py
  yaksh/templates/yaksh/course_modules.html
  yaksh/templates/yaksh/quizzes_user.html
  yaksh/templates/yaksh/view_profile.html
  yaksh/test_models.py
Labels: Type: Bug, Type: Enhancement

#452 Add a management command to add users to moderator group
  CHANGELOG.txt
  yaksh/management/commands/add_group.py
  yaksh/management/commands/create_moderator.py
Labels: Type: Enhancement

#455 Deprecate multiple management commands
  CHANGELOG.txt
  yaksh/management/commands/dump_user_data.py
  yaksh/management/commands/load_exam.py
  yaksh/management/commands/load_questions_xml.py
  yaksh/management/commands/results2csv.py
Labels: Type: Enhancement

#456 Preview QuestionPaper as an HTML
  yaksh/templates/yaksh/courses.html
  yaksh/templates/yaksh/preview_questionpaper.html
  yaksh/test_views.py
  yaksh/urls.py
  yaksh/views.py
Labels: Type: Feature

#434 Arrange options question type
  .coveragerc
  yaksh/evaluator_tests/test_simple_question_types.py
  yaksh/forms.py
  yaksh/models.py
  yaksh/static/yaksh/js/jquery-sortable.js
  yaksh/static/yaksh/js/requesthandler.js
  yaksh/templates/yaksh/add_question.html
  yaksh/templates/yaksh/grade_user.html
  yaksh/templates/yaksh/question.html
  yaksh/templates/yaksh/user_data.html
  yaksh/templates/yaksh/view_answerpaper.html
  yaksh/templatetags/custom_filters.py
  yaksh/templatetags/test_custom_filters.py
  yaksh/test_models.py
  yaksh/views.py
Labels: Type: Feature

#438 Grades
  .travis.yml
  grades/__init__.py
  grades/admin.py
  grades/apps.py
  grades/forms.py
  grades/migrations/0001_initial.py
  grades/migrations/__init__.py
  grades/migrations/default_grading_system.py
  grades/models.py
  grades/templates/add_grades.html
  grades/templates/grading_systems.html
  grades/tests/__init__.py
  grades/tests/test_models.py
  grades/tests/test_views.py
  grades/urls.py
  grades/views.py
  online_test/settings.py
  online_test/urls.py
  yaksh/forms.py
  yaksh/models.py
  yaksh/templates/manage.html
  yaksh/templates/yaksh/course_detail.html
  yaksh/templates/yaksh/course_modules.html
  yaksh/templates/yaksh/courses.html
  yaksh/templatetags/custom_filters.py
  yaksh/test_models.py
  yaksh/views.py
Labels: Type: Feature
