Repository FOSSEE/online_test, pull requests merged in 2018-02, with the labels that each got.

#417 Change time_between_attempts field unit Hours
  yaksh/models.py
  yaksh/test_models.py
Labels: Type: Enhancement

#430 Fix multiple Answerpaper objects returned error
  yaksh/models.py
  yaksh/test_models.py
Labels: Type: Bug

#436 Additions and fixes for lesson feature
  yaksh/forms.py
  yaksh/live_server_tests/selenium_test.py
  yaksh/models.py
  yaksh/templates/404.html
  yaksh/templates/yaksh/complete.html
  yaksh/templates/yaksh/courses.html
  yaksh/templates/yaksh/design_questionpaper.html
  yaksh/test_models.py
  yaksh/test_views.py
  yaksh/views.py
Labels: Type: Bug, Type: Enhancement

#444 Fix README.rst
  README.rst
Labels: Type: Documentation
