Repository FOSSEE/online_test, pull requests merged in 2019-01, with the labels that each got.

#543 Ensure that the displayed Answers escape special characters
  yaksh/templates/yaksh/grade_user.html
  yaksh/templates/yaksh/preview_questionpaper.html
  yaksh/templates/yaksh/user_data.html
  yaksh/templates/yaksh/view_answerpaper.html
Labels: Type: Enhancement

#510 Fetch only distinct values for courses where User is Creator OR Teacher
  yaksh/templates/500.html
  yaksh/views.py
Labels: Priority: Critical, Type: Bug

#538 [UI] Fix Monitor in Moderator interface:
  yaksh/templates/base.html
  yaksh/templates/manage.html
  yaksh/templates/yaksh/user_data.html
Labels: Type: Enhancement

#537 [UI] Multiple UI Fixes in New UI
  yaksh/templates/manage.html
  yaksh/templates/user.html
  yaksh/templates/yaksh/course_detail.html
  yaksh/templates/yaksh/course_modules.html
  yaksh/templatetags/custom_filters.py
Labels: Priority: High, Type: Enhancement

#532 Fix Create Question Paper CSS and JS
  yaksh/static/yaksh/css/question_paper_creation.css
  yaksh/static/yaksh/js/question_paper_creation.js
  yaksh/templates/base.html
  yaksh/templates/yaksh/design_course_session.html
  yaksh/templates/yaksh/design_questionpaper.html
Labels: Priority: Critical, Type: Enhancement
